Added Metrics component with charts also added world map
chingu-voyages/v45-tier2-team-25 pull request #18
Opened 2023-08-26 04:29 UTC by Yuroq

### What has been done?

- Added Total number of strikes chart
- Added Average mass chart
- Added Number of strikes by year chart
- Added Number of strikes by meteorite composition chart
- Added World Map with markers that are placed on meteor location with details of meteor in the tooltip

### Usage
### Charts:
 Charts are stored in multiple files (file for each chart) but all combined in the "AllCharts.jsx" file located inside of "MetricComponent" folder. "AllCharts" component is called in the "CardPage.jsx"

### Map:
 File name is "WorldMap.jsx" Stored in the "WorldMap" folder, WorldMap component is called in the "HomePage.jsx" file.

2023-08-26 16:33 UTC, fm-anderson commented on package.json
> +    "install": "^0.13.0",
Could you please clarify the purpose of this dependency?

2023-08-26 16:33 UTC, fm-anderson commented on package.json
> +    "npm": "^9.8.1",
Could you please clarify the purpose of this dependency?

2023-08-26 16:34 UTC, fm-anderson commented on src/routes/MetricComponent/AllCharts.jsx
Can you please fix the indentation? This will help avoid merge conflicts in the future.

2023-08-26 16:35 UTC, fm-anderson commented on src/routes/MetricComponent/MassChart.jsx
Can you please fix the indentation? This will help avoid merge conflicts in the future.

2023-08-26 16:35 UTC, fm-anderson commented on src/routes/MetricComponent/MeteorComposition.jsx
Can you please fix the indentation? This will help avoid merge conflicts in the future.

2023-08-26 16:35 UTC, fm-anderson commented on src/routes/MetricComponent/StrikesByYear.jsx
Can you please fix the indentation? This will help avoid merge conflicts in the future.

2023-08-26 16:35 UTC, fm-anderson commented on src/routes/MetricComponent/TotalStrikes.jsx
Can you please fix the indentation? This will help avoid merge conflicts in the future.

2023-08-26 16:36 UTC, fm-anderson commented on src/routes/WorldMap/WorldMap.jsx
Can you please fix the indentation? This will help avoid merge conflicts in the future.

2023-08-26 16:42 UTC, fm-anderson requested changes
## Dependencies
Hi Jamal, there are a few dependencies that I don’t understand.
- `npm`: Looks like you installed npm on the project folder. I'd recommend installing it globally on your computer.
- `install`: Not sure what's the propose of this one. Can you clarify?
  
## Indentation
Can you please review the indentation of the files you've created? They have lots of unnecessary empty lines, and it's hard to read due to the amount of indentation. I'd recommend adding prettier to your vs code, but you can also add it as a project dependency if you don't want to have it on your VS code.

You can find more details about prettier here: https://www.npmjs.com/package/prettier

2023-08-26 16:56 UTC, fm-anderson commented on src/routes/MetricComponent/AllCharts.jsx
> +import React from "react";
No need to import `React`

2023-08-26 16:57 UTC, fm-anderson commented on src/routes/MetricComponent/MassChart.jsx
> +import React, { PureComponent, useState, useEffect } from 'react';
`PureComponent` is imported but never used.

2023-08-26 16:57 UTC, fm-anderson commented on src/routes/MetricComponent/MeteorComposition.jsx
> +import React, { useState, useEffect } from "react";
No need to import `React`.

2023-08-26 21:10 UTC, Yuroq commented on package.json
> +    "npm": "^9.8.1",
npm and install dependencies have no use I may have installed them on accident trying to install something else. I deleted both dependencies.

2023-08-27 09:30 UTC, fm-anderson approved these changes
Thank you Jamal! Great work. The map looks awesome!

2023-08-27 09:31 UTC, merged